### PR TITLE
Try to switch pin from ACPI Mode to GPIO Driver Mode

### PR DESCRIPTION
**Pull request by averycblack**
Chromebooks leave this register at the default value of zero it seems. I'm not sure if writing to this register ever fails, so I left the check in the return statement.

Could this help out other problematic machines which didn't have the right bits set?

### CODE REVIEW

**Comment by averycblack** [comment]
https://www.intel.com/content/www/us/en/content-details/332691/intel-100-series-chipset-family-platform-controller-hub-pch-datasheet-volume-2.html
I didn't see any restrictions writing to this register while looking at this, but maybe I'm missing something obvious. Is it alright to be writing to this register? If we're using it for an I2C device, I sort of doubt that the firmware/ACPI is using it for something else.

**Comment by kprinssu** [comment]
@1Revenger1 Can you tag me on PRs for this repository? 
As well as also updating and fixing the conflicts? I will merge the changes in and also create a new release of VoodooI2C.

**Comment by averycblack** [comment]
@kprinssu Sorry about the delay, was busy the past couple of days.
I just rebased on top of master though, so should be good to go.

**Comment by kprinssu** [comment]
Thanks @1Revenger1! I appreciate the PR!

**Review by kprinssu — APPROVED** [review]

**Pull request merged**
